name: SignalDart
version: 0.0.1
author: Darren Reid <layoric@gmail.com>
description: A package to help use SignalR JS client with Dart
homepage: https://github.com/Layoric/SignalDart
documentation: https://github.com/Layoric/SignalDart
dependencies:
  async: any
  browser: any
  json_client: any
